version: '3'

volumes:
  mysql_data:
    driver: local

networks:
  dev:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 9216

services:
  mysql:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD-root}
      MYSQL_DATABASE: ${DB_NAME-keycloak}
      MYSQL_USER: ${DB_USER-keycloak}
      MYSQL_PASSWORD: ${DB_PASSWORD-password}
    networks:
      - dev

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: ${DB_NAME-keycloak}
      DB_USER: ${DB_USER-keycloak}
      DB_PASSWORD: ${DB_PASSWORD-password}
      KEYCLOAK_USER: ${KEYCLOAK_USER-admin}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD-admin}
    ports:
      - 8180:8080
    depends_on:
      - mysql
    networks:
      - dev

  keycloak-config-cli:
    profiles:
      - config
    image: adorsys/keycloak-config-cli:latest
    environment:
      KEYCLOAK_URL: http://keycloak:8080/auth
      KEYCLOAK_USER: ${KEYCLOAK_USER-admin}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD-admin}
      KEYCLOAK_AVAILABILITYCHECK_ENABLED: ${KEYCLOAK_AVAILABILITYCHECK_ENABLED-true}
      KEYCLOAK_AVAILABILITYCHECK_TIMEOUT: ${KEYCLOAK_AVAILABILITYCHECK_TIMEOUT-120s}
      IMPORT_PATH: /keycloak_config
      IMPORT_FORCE: ${IMPORT_FORCE-false}
      DEBUG: ${DEBUG-false}
    volumes:
      - "./keycloak_config:/keycloak_config"
    depends_on:
      - keycloak
    networks:
      - dev

