version: '3'

volumes:
  postgres_data:
    driver: local

networks:
  dev:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 9216

services:
  postgres:
    image: docker-registry-dev-proxy.internal.stuart.com/postgres:12
    environment:
      POSTGRES_DB: ${DB_NAME-keycloak}
      POSTGRES_USER: ${DB_USER-keycloak}
      POSTGRES_PASSWORD: ${DB_PASSWORD-password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dev

  keycloak: &keycloak
    image: quay.io/keycloak/keycloak:11.0.0
    environment: &keycloak-enviroment
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: ${DB_NAME-keycloak}
      DB_USER: ${DB_USER-keycloak}
      DB_PASSWORD: ${DB_PASSWORD-password}
      KEYCLOAK_USER: ${KEYCLOAK_USER-admin}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD-admin}
    ports:
      - 8180:8080
    depends_on:
      - postgres
    networks:
      - dev

  keycloak-export:
    << : *keycloak
    profiles:
      - init
    environment:
      << : *keycloak-enviroment
    command: "-Dkeycloak.migration.action=export -Dkeycloak.migration.realmName=stuart -Dkeycloak.migration.provider=singleFile -Dkeycloak.migration.usersExportStrategy=SKIP -Dkeycloak.migration.file=/init_config/export.json"
    volumes:
      - "./init_config:/init_config"
    depends_on:
      - postgres
    networks:
      - dev

  keycloak-config-cli:
    profiles:
      - config
    image: adorsys/keycloak-config-cli:latest
    env_file:
      - .client_secrets.env
    environment:
      KEYCLOAK_URL: http://keycloak:8080/auth
      KEYCLOAK_USER: ${KEYCLOAK_USER-admin}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD-admin}
      KEYCLOAK_AVAILABILITYCHECK_ENABLED: ${KEYCLOAK_AVAILABILITYCHECK_ENABLED-true}
      KEYCLOAK_AVAILABILITYCHECK_TIMEOUT: ${KEYCLOAK_AVAILABILITYCHECK_TIMEOUT-120s}
      IMPORT_PATH: /keycloak_config
      IMPORT_FORCE: ${IMPORT_FORCE-false}
      DEBUG: ${DEBUG-false}
      IMPORT_VARSUBSTITUTION: 1
      IMPORT_VARSUBSTITUTION_IN_VARIABLES: 1
      IMPORT_VARSUBSTITUTION_UNDEFINED_THROWS_EXCEPTIONS: 1
    volumes:
      - "./keycloak_config:/keycloak_config"
    depends_on:
      - keycloak
    networks:
      - dev

  keycloak-cli:
    << : *keycloak
    profiles:
      - cli
    entrypoint: /opt/jboss/keycloak/bin/kcadm.sh
    volumes:
      - "./.config_cli:/opt/jboss/.keycloak"

  keycloak-init: &keycloak-init
    << : *keycloak
    profiles:
      - init
    image: quay.io/keycloak/keycloak:11.0.0
    environment:
      << : *keycloak-enviroment
      KEYCLOAK_IMPORT: "/init_config/.current/realm-export-full.json"
    command: "-Dkeycloak.profile.feature.scripts=enabled -Dkeycloak.profile.feature.upload_scripts=enabled"
    volumes:
      - "./init_config:/init_config"
    depends_on:
      - postgres
    networks:
      - dev

  keycloak-cli-init:
    << : *keycloak-init
    profiles:
      - cli
    entrypoint: /opt/jboss/keycloak/bin/kcadm.sh
    volumes:
      - "./init_config:/init_config"
      - "./.config_cli:/opt/jboss/.keycloak"

  jq-processor:
    profiles:
      - cli
    image: stedolan/jq
    volumes:
      - "./init_config:/init_config"
